# sources.yml
version: 2

sources:
  - name: international_football
    database: airflow-data-pipeline-404012 # Put the project id!

    tables:
      - name: raw_results
      - name: raw_goalscorers
      - name: raw_shootouts