# sources.yml
version: 2

sources:
  - name: international_football
    database: your-project-id # Put the Google Cloud project id!

    tables:
      - name: raw_results
      - name: raw_goalscorers
      - name: raw_shootouts