# profiles.yml

international_football:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: your-project-id # Change this to your GC project id 
    dataset: international_football 
    threads: 1
    timeout_seconds: 300
    location: US